dist: focal
sudo: true
addons:
  apt:
    packages:
      - qemu-kvm
      - qemu-utils
      - libmnl-dev
language: go
go:
  - 1.15.x

before_script:
  # See https://github.com/codeclimate/test-reporter/blob/master/examples/go_examples.md
  - curl --retry 5 -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - GO111MODULE=off go get github.com/mattn/goveralls
script:
  # HACK: /dev/kvm is root:kvm 0660 by default
  - sudo chmod 666 /dev/kvm
  - make gokvm
  - make test
  - goveralls -service=travis-ci
  - make clean
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
- provider: script
  skip_cleanup: true
  script: curl --retry 5 -sL https://git.io/goreleaser | bash
  on:
    tags: true
