dist: focal
sudo: true
addons:
  apt:
    packages:
      - qemu-kvm
      - qemu-utils
      - libmnl-dev
language: go
go:
  - 1.17.x

before_script:
  # See https://github.com/codeclimate/test-reporter/blob/master/examples/go_examples.md
  - curl --retry 5 -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod a+x ./cc-test-reporter
  - sudo -E env "PATH=$PATH" ./cc-test-reporter before-build
  - sudo -E env "PATH=$PATH" "GO111MODULE=off" go get github.com/mattn/goveralls
  - sudo -E env "PATH=$PATH" make golangci-lint initrd vda.img
  - sudo -E env "PATH=$PATH" make -j $(nproc) bzImage
script:
  - sudo -E env "PATH=$PATH" make gokvm
  - sudo -E env "PATH=$PATH" make test
after_script:
  - sudo -E env "PATH=$PATH" goveralls -service=travis-ci -coverprofile c.out
  - sudo -E env "PATH=$PATH" ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - sudo -E env "PATH=$PATH" make clean
deploy:
- provider: script
  skip_cleanup: true
  script: curl --retry 5 -sL https://git.io/goreleaser | bash
  on:
    tags: true
